version: "3"

services:
  zepelin:
    build: "."
    ports:
      - "8787:8080"
    volumes:
      - "./logs:/zeppelin/logs:rw"
      - "./notebook:/zeppelin/notebook:rw"
    environment:
      - "ZEPPELIN_LOG_DIR=/zeppelin/logs"
      - "ZEPPELIN_NOTEBOOK_DIR=notebook"
    container_name: "uol_zeppelin"
